<?php
$currentProduct = $this->getProduct();
$regularPrice = $currentProduct->getPriceInfo()->getPrice('regular_price');
?>

<p>
  <label for="amount">Price range:</label>
  <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
</p>

<div id="slider-range"></div>

<script>
    require([
        'jquery',
        'priceslider'], function ($) {
        $( function() {
        	var minprice = '<?php echo $regularPrice->getMinRegularAmount(); ?>';
        	var maxprice = '<?php echo $regularPrice->getMaxRegularAmount(); ?>';
        	console.log(minprice, '------><><-----', parseInt(maxprice));
		    $( "#slider-range" ).slider({
		      range: true,
		      min: parseInt(minprice),
		      max: parseInt(maxprice),
		      values: [ parseInt(minprice), parseInt(maxprice) ],
		      slide: function( event, ui ) {
		        $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
		      }
		    });
		    $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
		      " - $" + $( "#slider-range" ).slider( "values", 1 ) );
		});
    });
</script>
